users:
  - name: personal
    groups: wheel,docker,libvirt
  - name: work
    groups: docker

screen:
  dpi: 120
  scale: 1.25

video: intel
# video: amd

eth_iface: enp7s0
system_partition: sda3

virt: false
battery: true
backlight: true

colors:
  normal:
    black:   '5c6370'
    red:     'e06c75'
    green:   '98c379'
    yellow:  'e5c07b'
    blue:    '61afef'
    magenta: 'c678dd'
    cyan:    '56b6c2'
    white:   'abb2bf'
  bright:
    black:   '4b5263'
    red:     'be5046'
    green:   '98c379'
    yellow:  'd19a66'
    blue:    '61afef'
    magenta: 'c678dd'
    cyan:    '56b6c2'
    white:   '3e4452'

font:
  sans:
    family: Fira Sans
    size: 11
  monospace:
    family: Fantasque Sans Mono
    size: 12
# screen:
#   dpi: 128
#   scale: 1.33333333

# screen:
#   dpi: 120
#   scale: 1.25

# screen:
#   dpi: 144
#   scale: 1.5

github_notifications_token: 0
